import { QuestionnaireData } from '@/store/usePrdStore';

export function generateProfessionalPrd(q: QuestionnaireData): { markdown: string; estimatedHours: number } {
  const appTitle = q.appCategory ? `${q.appCategory}` : 'Aplikasi SaaS & CRM Enterprise';
  const target = q.targetAudience || 'Pengembang, Konsultan Digital, & Tim Manajemen Proyek';
  const features = q.keyFeatures || 'Otomatisasi PRD dengan AI, DevPulse Live Canvas Visual CMS, Pipeline Deals, dan Kanban Board';
  const scale = q.userScale || '10.000 - 50.000 Pengguna Aktif Bulanan';
  const refApp = q.referenceApp || 'DevPulse Studio Pro Suite (Dark Cyber Glassmorphism)';
  const timeline = q.timeline || '4 - 6 Minggu';

  const estimatedHours = 160;

  const markdown = `# PRD.md: ${appTitle}
> **Document Version:** \`v1.0.0-PROD\` | **Target Stack:** \`Next.js PWA + Express + Supabase\` | **Generated by:** \`DevPulse AI Architect Engine\`

---

## 1. Ringkasan Eksekutif & Problem Statement

### 1.1 Latar Belakang & Masalah
Dalam ekosistem digital saat ini, proses perancangan spesifikasi aplikasi (*scoping*), estimasi biaya, dan manajemen *pipeline* klien kerap memakan waktu berminggu-minggu serta rentan terhadap *misconception* teknis antara klien dan pengembang. Proyek **${appTitle}** dibangun sebagai solusi terpadu untuk mengotomatisasi penyusunan dokumen PRD.md, memberikan kalkulasi tarif transparan, serta menyediakan *visual workspace* modern.

### 1.2 Target Audiens & Persona Pengguna
- **Target Pengguna Utama:** ${target}
- **Skala Beban Sistem:** ${scale}
- **Referensi Desain & UX:** Terinspirasi dari ${refApp} dengan tema *Dark Cyber Glassmorphism*.

### 1.3 Nilai Tambah Utama (Key Value Propositions)
1. **Penyusunan PRD Instan:** Menghasilkan dokumen spesifikasi teknis lengkap dengan diagram alur dalam waktu hitungan menit.
2. **Kalkulasi Biaya 100% Transparan:** Tanpa biaya tersembunyi, dihitung berdasarkan rumus formula transparan \`Total Jam Kerja × Rate Per Jam\`.
3. **Manajemen Proyek Terpadu:** Dilengkapi Kanban Board, Deals Pipeline, dan CMS visual interaktif.

---

## 2. Arsitektur Sistem & Data Flow

Berikut adalah rancangan arsitektur sistem multi-tier berstandar *Enterprise Cloud*:

\`\`\`mermaid
flowchart TD
    subgraph ClientTier ["🖥️ Client Tier (Frontend PWA)"]
        A1["Next.js 16 + React 19"] --> A2["Tailwind CSS + Glassmorphism"]
        A2 --> A3["Zustand State Management"]
        A3 --> A4["Framer Motion + AnimeJS"]
    end

    subgraph GatewayTier ["🛡️ Security & API Gateway"]
        B1["Rate Limiter (Express Limit)"] --> B2["Better Auth + JWT Guard"]
        B2 --> B3["CORS + Helmet Security Headers"]
    end

    subgraph BackendTier ["⚙️ Application Core Tier"]
        C1["Express.js 5 REST API"] --> C2["Auth & RBAC Middleware"]
        C2 --> C3["AI Orchestration Service"]
        C3 --> C4["Prisma ORM Client"]
    end

    subgraph DataTier ["🗄️ Database & Cloud Tier"]
        D1[("Supabase PostgreSQL")]
        D2[("Supabase Bucket Storage")]
        D3["AI LLM Provider Engine"]
    end

    ClientTier --> GatewayTier
    GatewayTier --> BackendTier
    BackendTier --> DataTier
\`\`\`

---

## 3. User Journey & Core Business Logic Flow

Diagram interaksi alur kerja pengguna dari *onboarding* verifikasi keamanan hingga penerbitan dokumen PRD:

\`\`\`mermaid
sequenceDiagram
    autonumber
    actor User as Klien / User
    participant Frontend as Next.js PWA Client
    participant Captcha as Puzzle CAPTCHA Gate
    participant AI as AI PRD Engine
    participant DB as Supabase Database

    User->>Frontend: Buka Landing Page & Mulai PRD Builder
    Frontend->>Captcha: Munculkan Verifikasi Puzzle Anti-Bot
    User->>Captcha: Geser puzzle ke posisi yang tepat
    Captcha-->>Frontend: Token Terverifikasi (Success Snap)
    
    User->>Frontend: Isi Kebutuhan Aplikasi (Questionnaire)
    Frontend->>AI: Kirim parameter (${q.appCategory || 'Kebutuhan Klien'})
    AI-->>Frontend: Generate Live PRD.md + Diagram Mermaid
    
    User->>Frontend: Review Hasil & Klik 'Setujui PRD & Submit Kontak'
    Frontend->>DB: Simpan Lead Prospek & Dokumen PRD
    DB-->>Frontend: Data Berhasil Disimpan (Lead Converted)
    Frontend-->>User: Konfirmasi Sukses & Pengalihan Kontak WhatsApp
\`\`\`

---

## 4. Skema Database & Entity Relationship Diagram (ERD)

Relasi antar entitas data dirancang secara ternormalisasi dengan integritas *Foreign Key*:

\`\`\`mermaid
erDiagram
    USER {
        uuid id PK
        string email UK
        string name
        string role
        datetime createdAt
    }
    LEAD_DEAL {
        uuid id PK
        string appTitle
        string companyName
        string contactPhone
        string email
        text prdContent
        int estimatedHours
        bigint totalCost
        string stage
        uuid assignedTo FK
        datetime createdAt
    }
    TASK_KANBAN {
        uuid id PK
        uuid dealId FK
        string title
        text description
        string priority
        string status
        int order
        datetime dueDate
    }
    ACTIVITY_LOG {
        uuid id PK
        uuid userId FK
        string action
        string entityType
        datetime timestamp
    }

    USER ||--o{ LEAD_DEAL : "manages"
    LEAD_DEAL ||--o{ TASK_KANBAN : "contains"
    USER ||--o{ ACTIVITY_LOG : "triggers"
\`\`\`

---

## 5. Rincian Fitur Utama & User Stories

### Fitur Terpilih:
${features.split(',').map((f) => `- **${f.trim()}**: Dirancang modular untuk mendukung skalabilitas tinggi.`).join('\n')}

### 5.1 User Story: Verifikasi Puzzle Anti-Bot & AI Scoping
- **As a** Calon Klien / Product Owner,
- **I want to** menyelesaikan verifikasi puzzle anti-bot dan memasukkan kebutuhan fitur proyek,
- **So that** saya mendapatkan dokumen spesifikasi PRD.md yang terstruktur secara instan tanpa khawatir kuota token disalahgunakan oleh bot.

**Kriteria Penerimaan (Acceptance Criteria):**
- [ ] **Given** pengguna berada di langkah 1, **When** pengguna menggeser kepingan puzzle tepat pada lubang target ($\pm 10\text{px}$), **Then** sistem memberikan konfirmasi visual sukses dan membuka wizard form.
- [ ] **Given** form kuesioner terisi lengkap, **When** pengguna mengklik tombol *Generate*, **Then** sistem menampilkan dokumen PRD lengkap beserta diagram Mermaid secara *real-time*.

### 5.2 User Story: Manajemen Deals Pipeline & Kanban Board
- **As an** Admin / Konsultan Digital,
- **I want to** memindahkan status prospek klien menjadi *Deals* dan mengelola kartu tugas di Kanban Board,
- **So that** seluruh proses pengerjaan aplikasi terpantau dengan jelas hingga tahap rilis.

---

## 6. Spesifikasi API Endpoints & Keamanan

| Method | Endpoint | Deskripsi | Auth Required | Role |
| :--- | :--- | :--- | :--- | :--- |
| \`POST\` | \`/api/v1/auth/login\` | Autentikasi Admin & Penerbitan JWT | Tidak | Publik |
| \`GET\` | \`/api/v1/leads\` | Mengambil daftar prospek lead submission | Ya | Admin / Staff |
| \`POST\` | \`/api/v1/leads\` | Submit prospek klien dari PRD Builder | Tidak | Publik + CAPTCHA |
| \`GET\` | \`/api/v1/deals\` | Mengambil data pipeline deals & status | Ya | Admin |
| \`POST\` | \`/api/v1/tasks\` | Membuat kartu tugas baru di Kanban | Ya | Admin / Developer |
| \`PUT\` | \`/api/v1/tasks/reorder\` | Update urutan kolom drag-and-drop Kanban | Ya | Admin / Developer |

---

## 7. Estimasi Waktu Development & Alokasi Sprint

Rincian modul pengerjaan transparan selama **${timeline}**:

| No | Modul Pekerjaan | Deskripsi Teknis | Estimasi Waktu |
| :--- | :--- | :--- | :--- |
| 1 | **Foundation & Auth Security** | Setup Next.js PWA, Express API, Better Auth + JWT Token | 40 Jam |
| 2 | **AI PRD Builder & Puzzle CAPTCHA** | Wizard Questionnaire, Mermaid Parser, & Anti-Bot Protection | 45 Jam |
| 3 | **CRM Pipeline & DevPulse Kanban** | Deals Management, Drag-and-Drop Task Board, Master Data | 45 Jam |
| 4 | **DevPulse Live Canvas Visual CMS** | Live Preview Canvas, Image Upload Supabase, Viewport Toggle | 30 Jam |
| **TOTAL** | **Total Estimasi Jam Kerja** | **Garansi Rate 100% Transparan** | **${estimatedHours} Jam** |

> 💰 **Kalkulasi Biaya Investasi Proyek:**
> $$\text{Total Biaya} = 160\text{ Jam} \times \text{Rp } 250.000 = \mathbf{\text{Rp } 40.000.000}$$

---

## 8. Standar Kualitas & Non-Functional Requirements (NFR)

1. **Performa Kecepatan:** *Largest Contentful Paint (LCP)* wajib $< 2.5\text{ detik}$, responsivitas API $p95 < 200\text{ms}$.
2. **Keamanan Data:** Implementasi *Supabase Row Level Security (RLS)*, enkripsi password *Bcrypt*, serta sanitasi input terhadap serangan *XSS* dan *SQL Injection*.
3. **Desain & Responsivitas:** Mendukung penuh *Mobile & Tablet First* serta resolusi Desktop Monitor dengan *Dark Mode Glassmorphism*.
`;

  return { markdown, estimatedHours };
}
